name: Deploy Lambda

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::603195189317:role/Github2
          aws-region: ca-central-1   # ou la région où est ta Lambda
     
      - name: Test AWS CLI
        run: aws sts get-caller-identity
      
      - name: Deploy to Lambda
        run: |
              zip -r function.zip .
              aws lambda update-function-code \
                --function-name arn:aws:lambda:ca-central-1:603195189317:function:Test \
                --zip-file fileb://function.zip

